/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
    id("edu.sc.seis.launch4j") version "3.0.5"
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("org.beryx.jlink") version "3.0.1"
}


jlink {
    // options.set(listOf("--strip-debug", "--no-header-files", "--no-man-pages"))
    launcher {
        name = "SubsetSum"
        // jvmArgs = listOf("-Dlog4j.configurationFile=./log4j2.xml")
    }
    application {
        mainModule.set("calculategui")
        mainClass.set("calculategui.App")
    }
}

javafx {
    version = "21"
    modules = listOf("javafx.controls", "javafx.fxml")
}

tasks {
    shadowJar {
        archiveClassifier.set("")
        manifest {
            attributes["Main-Class"] = "calculategui.App"
        }
    }
    launch4j {
        icon.set("${projectDir}/src/main/resources/SubsetSubIcon.ico")
        outfile.set("SubsetSum.exe")
        headerType.set("gui")
    }
}

application {
    // Define the main class for the application.
    mainClass.set("calculategui.App")
}



repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation("org.openjfx:javafx-controls:21")
    implementation("org.openjfx:javafx-fxml:21")
}